---
title: ""
author: ""
format: pdf
editor: visual
---

# Aula do dia 27/06/2022

**Adequabilidade dos dados**

- Tese de esfericidade de **Bartlett**
    - **IMPORTANTE**: $H_{0}$: *A matrix de correlação é uma matriz identidade*

Função `R`

```{r}
#install.packages("MVTests", dependencies = T)
data(iris)
results <- MVTests::Bsper(data=iris[,1:4])
summary(results)
```

- Função própria

```{r}
bartlett = function(M){
    n = dim(M)[1]
    p = dim(M)[2]
    R = det(cor(M))
    value = -((n-1) - (2*p+5)/6)*log(R)
    v = (p*(p-1))/2
    QuiQuadrado = pchisq(value, v)
    print(list(
    sprintf(paste('O valor da Estatísica de Barlett é', round(value,3))),
    sprintf(paste('QuiQuadrado é', round(QuiQuadrado,3)))
    ))
}

bartlett(iris[,1:4])
```


- Medida de adequabilidade da amostra de **Kaiser-Meyer-Olkin(KMO)**

Função `R`

```{r }
#install.packages("psych", dependencies = T)
#psych::KMO()
```

Função própria

```{r}
KMO1 = function(M){
      num = sum(M^2) - diag(M)
      den = (sum(M^2) - diag(M)) - (sum(cor(M)^2 - diag(cor(M))))
      kmo = num/dem
      print(kmo)
}
```

